connectrpc/connectrpc.com

- docs/protocol.md
This adds code formatting (i.e. `deadline_exceeded`) to the error codes in docs to make it a bit easier to read.
> Add code formatting to error codes

- docs/protocol.md
The correct key for unary GETs is `message`, not `msg`.
> Fix incorrect example in protocol ref

- docs/swift/interceptors.md
Updates the documentation to reflect the changes in https://github.com/connectrpc/connect-swift/pull/186.
The copy matches `Interceptor.swift`'s inline documentation from that PR with the addition of an auth example here.
> Update docs for Swift interceptors

- docs/node/using-clients.md
- docs/web/cancellation-and-timeouts.mdx
- docs/web/choosing-a-protocol.mdx
This fixes a few places in the docs that say `gRCP`.
> Fix occurrences of 'gRCP'

- .github/workflows/add-to-project.yaml
This allows the add-to-project workflow to work on forks.
> Fix issue with workflow on forks

- .github/CONTRIBUTING.md
In the description of how contributors should propose changes to the
documentation, I omitted the step where they actually open a pull
request.
> Add missing step to CONTRIBUTING.md

- static/conformance.html
- vercel.json
Still unclear if we want to do this, since the conformance repo has no import-able Go code. But if we want to leave its `go.mod` and existing imports in the `v1` branch alone (which, for consistency, uses a connectrpc.com vanity domain like our other Connect Go packages) and make the test runner install-able via `go install ...`, we need this in place.
> Add vanity import for connectrpc/conformance

- docs/curl-and-other-clients.md
Add examples for Connect GET requests with cURL and fetch to the page "cURL & other clients".
> Add cURL and fetch examples for Connect GET

- docs/web/query.mdx
Our vercel.json currently specifies a `permanent` redirect from `/docs/web/query/` and `/web/query/` to `/docs/web/query/getting-started` which means we have to match that path name or 404s will through on full refresh.
> Add redirect to catch other redirects

- docs/governance/rfc/002-go-cors-authn.md
- docs/governance/rfc/_category_.yml
Add an RFC for creating CORS and authentication packages for users of
Connect in Go.
> Add RFC-002: CORS and authn for Go

- static/authn.html
- static/cors.html
- vercel.json
Add the plumbing required to resolve the connectrpc.com/authn and
connectrpc.com/cors import paths (proposed and approved in #123).
> Add Go module support for cors and authn

- docs/cors.md
- docs/go/deployment.md
Use our new helpers in the CORS documentation.
> Use connectrpc.com/cors in CORS docs

- docs/go/observability.md
Correct the observability examples for the API changes. NewInterceptor now returns an error and the naming for the propagator is corrected.
Thanks to https://bufbuild.slack.com/archives/CRZ680FUH/p1705146367965609 for finding the issue.
> Fix Go observability options example

- docs/node/implementing-services.md
- docs/node/interceptors.md
- docs/node/server-plugins.md
- docs/node/testing.md
- docs/node/using-clients.md
- docs/web/interceptors.mdx
Add connect-node interceptor documentation. Will merge after we release.
> Add connect-node interceptor docs.

- docs/governance/rfc/003-http-codes.md
Introduce RFC 003, which proposes amending the mappings between Connect
error codes and HTTP status codes. The amendments fix a potentially
serious bug and improve gRPC interoperability.
The concrete changes proposed are in #130.
> RFC 003: Amend Connect HTTP codes

- docs/protocol.md
None of the actual client implementations require that the Connect RPC code and the HTTP code are aligned (which is actually good since it allowed us to improve the mappings (#130) without it being a breaking change in practice).
This updates the language in the spec to make it a little more clear that a client should not necessarily treat it as an error if the Connect RPC code and HTTP status code do not agree. Admittedly, this is a rather subtle single word change. We could be even more explicit about what clients should do. But I think that might be better saved for a future document that provides a more _behavior_-focused spec (vs. protocol/wire-format-focused), which can also include guidance and requirements about other things that are today only codified in [conformance test …
> Soften the language regarding error codes and HTTP codes with the Connect unary protocol

- docs/faq.md
The FAQ is pretty consistent in the "connect-go" casing, so fixed one inconsistent instance. The FAQ goes back and forth on "connect-go" and "`connect-go`", though, so I did not make those consistent (not sure they need to be, though).
> Fix minor inconsistencies in FAQ

- docs/web/supported-browsers-and-frameworks.mdx
The current RN documentation suggests using [react-native-polyfill-globals](https://github.com/acostalima/react-native-polyfill-globals) which has not been updated in a few years. There have also been recent updates to RN negating the need for many of those polyfills. This PR updates the instructions to use a minimal number of newer and better maintained polyfills.
Some highlights:
- Drops react-native-polyfill-globals in favor of using RN's `polyfillGlobal` directly.
- Drops atob and btoa polyfills since hermes is now the default and includes atob and btoa.
- Replaces unmaintained [text-encoding](https://github.com/inexorabletash/text-encoding) with maintained and more performant [react-native-fast-encoder](https://github.com/maksimlya/react-native-fast-encoder). (Note that hermes does …
> Update RN polyfill instructions to use fewer & newer polyfills

- docs/web/supported-browsers-and-frameworks.mdx
This updates the React Native docs snippet around streaming to simply link to the issue and not mention prioritization (since it's largely out of our hands at the moment).
> Update React Native docs

- docs/node/getting-started.md
- docs/node/server-plugins.md
- docs/web/generating-code.mdx
- docs/web/getting-started.mdx
- docs/web/query.mdx
Currently, installing Protobuf-ES and Connect without specifying a version will fail because it will try to install v2.0 of Protobuf-ES and v1.0 of Connect. This updates the docs to pin _all_ dependences to `^1.0.0`.
Note that we should update these when a v2.0 of Connect is released.
> Update docs to pin to v1.x for Protobuf-ES

- docs/web/supported-browsers-and-frameworks.mdx
The RN polyfill updates in https://github.com/connectrpc/connectrpc.com/pull/182 work great for debug builds but have an issue in release builds. This updates the instructions to rectify this oversight.
> Fix RN Polyfills instructions for release builds

- docs/protocol.md
The protocol spec refers to an "object" for the optional debug data in Error and EndStreamResponse. Since some well-known Protobuf types such as `google.protobuf.Timestamp` serialize to a JSON value, not an object, the debug data can actually contain any JSON value.
> Clarify Connect error debug property type

- docs/go/headers-and-trailers.md
This PR fixes a minor issue in the documentation's error handling example. The original example incorrectly referenced `err` instead of `connectErr` when accessing metadata, which could lead to confusion.
- Updated the error handling example to correctly use `connectErr.Meta().Get("Greet-Version")` instead of `err.Meta().Get("Greet-Version")`.
> Fix docs correct error handling in golang Headers & trailers section

- docs/go/observability.md
Similar to https://github.com/connectrpc/otelconnect-go/pull/176.
> Add error handling to otelconnect examples

- docs/node/implementing-services.md
Port `/implementing-services` section to v2.
> es/v2: Port `/implementing-services`

- docs/web/using-clients.mdx
For context, see https://github.com/connectrpc/connectrpc.com/pull/218#discussion_r1824534972 and https://github.com/connectrpc/examples-es/pull/2049.
> es/v2: Restore the custom client section

- docs/dart/using-clients.md
Add `Using Clients` page to dart
> Add `Using Clients` page to dart

- package-lock.json
- package.json
- src/components/eliza-demo/index.tsx
This migrates the repo to use the v2 releases of Protobuf-ES and Connect.
> Migrate to v2 for Connect and Protobuf-ES

- docs/node/getting-started.md
- docs/web/generating-code.mdx
Including imports is not enabled by default in the Buf CLI. As a result, users have been getting tripped up on generating code when they have dependencies on protovalidate. 
This adds some additional guidance in our generating code docs to make sure they include imports since these should essentially always be included when generating with Protobuf-ES.
> Add additional options for generating imports

- docs/dart/getting-started.md
Add note about network permissions and web platform. For getting started, it will too much to also tell them how to configure a cross-platform http client.
> Add note about network permissions web platform

- MAINTAINERS.md
- docs/governance/rfc/005-python-implementation.md
I'd like to get a Python implementation officially accepted so we can focus our efforts on it.
This is a successor to #71 which I think is abandoned.
I have a prototype at https://github.com/firetiger-oss/connect-python/ which I'd like to see moved into the connectrpc organization. The current state of it is that it has synchronous and asynchronous clients, and a synchronous server (on WSGI).
It supports unary and streaming requests. It passes conformance tests, so it correctly handles the low-level details, including header and trailer metadata, with the configs here:
- sync client: https://github.com/firetiger-oss/connect-python/blob/main/tests/conformance/sync_config.yaml
- async client: https://github.com/firetiger-oss/connect-python/blob/main/tests/conformance/async_config.yaml
- …
> Add RFC 005: Python

- docs/go/observability.md
It should be from otel.GetMeterProvider, similar to the others (not whatever `global.MeterProvider` is).
And link out to pkg.go.dev, similar to the otelconnect references.
> Fix meter provider reference

- docs/go/deployment.md
Noticed that the deployment page had a section on observability that was a subset of the observability page and didn't mention otelconnect.
To keep current links working, just rework the section to link over to the page. (Otherwise, could just delete this section altogether.)
> Link connect-go deployment page to observability page

- docusaurus.config.js
- src/css/custom.css
- src/theme/Footer/styles.module.css
- src/theme/Navbar/MobileSidebar/Header/index.tsx
resolve issue mentioned in #299 
1. chevrons for the dropdown
2. CNCF logo in the bottom right corner is still dark
3. os preference
4. (extra) In mobile view, remove dark mode btn from navbar as it is already present on left side of search bar.
> fix: chevrons and CNCF logo in dark mode
